name: wimpy
channels:
  - defaults
dependencies:
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - pip=25.0
  - python=3.12.9
  - setuptools=75.8.0
  - tzdata=2025a
  - wheel=0.45.1
  - pip:
      - biopython==1.84
      - ipykernel==6.29.5
      - ipython==8.31.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - numpy==2.2.0
      - openpyxl==3.1.5
      - pandas==2.2.3
      - scipy==1.15.2
      - tqdm==4.67.1
