name: wimpy
channels:
  - defaults
dependencies:
  - python=3.12.8
  - setuptools=75.1.0
  - pip:
      - biopython==1.84
      - ipykernel==6.29.5
      - ipython==8.31.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - numpy==2.2.0
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pip==24.3.1
      - tqdm==4.67.1
